#ifndef __USER_WIFI_H__
#define __USER_WIFI_H__

#define WIFI_STA_ENABLE 1
#define WIFI_AP_ENABLE 0

#define DEST_WIFI_MAC "D4:DA:21:32:85:B6"
#define ESP_MAXIMUM_RETRY (5)

#define ESP_WIFI_AP_SSID "ESP32_clock"
#define ESP_WIFI_CHANNEL (1)
#define ESP_WIFI_AP_PASSWD ESP_WIFI_AP_SSID
#define MAX_STA_CONN 1

#define WIFI_CONNETED_AUTO_ENABLE_HTTP_SERVER 1

/********select wifi mode define********/
#define CONFIG_ESP_WPA3_SAE_PWE_HUNT_AND_PECK 1
#define CONFIG_ESP_WPA3_SAE_PWE_HASH_TO_ELEMENT 0
#define CONFIG_ESP_WPA3_SAE_PWE_BOTH 0

#define CONFIG_ESP_WIFI_AUTH_OPEN 0
#define CONFIG_ESP_WIFI_AUTH_WEP 0
#define CONFIG_ESP_WIFI_AUTH_WPA_PSK 0
#define CONFIG_ESP_WIFI_AUTH_WPA2_PSK 1
#define CONFIG_ESP_WIFI_AUTH_WPA_WPA2_PSK 0
#define CONFIG_ESP_WIFI_AUTH_WPA3_PSK 0
#define CONFIG_ESP_WIFI_AUTH_WPA2_WPA3_PSK 0
#define CONFIG_ESP_WIFI_AUTH_WAPI_PSK 0
/********************************************/

#define BIT1 0x00000002
#define BIT0 0x00000001
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT BIT1

#if CONFIG_ESP_WPA3_SAE_PWE_HUNT_AND_PECK
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HUNT_AND_PECK
#define EXAMPLE_H2E_IDENTIFIER ""
#elif CONFIG_ESP_WPA3_SAE_PWE_HASH_TO_ELEMENT
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HASH_TO_ELEMENT
#define EXAMPLE_H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#elif CONFIG_ESP_WPA3_SAE_PWE_BOTH
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_BOTH
#define EXAMPLE_H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#endif

#if CONFIG_ESP_WIFI_AUTH_OPEN
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_ESP_WIFI_AUTH_WEP
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_ESP_WIFI_AUTH_WPA_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WAPI_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

esp_err_t Show_Wifi_Info(void);

void User_WIFI_Init(void);

esp_err_t User_WIFI_disable_sta(void);

esp_err_t User_WIFI_changeConnection_sta(void);

esp_err_t User_WIFI_enable_AP(const char *ssid, const char *passwd,
                              size_t ssid_len);

esp_err_t User_WIFI_disable_AP(void);

esp_err_t show_wifi_list(void);

const char *GetConnect_AP_info(void);

int GetCurrentWifiMode(void);

cJSON *GetWifiInfo_JSON(void);

uint16_t GetWifiConnectStatus(void);

#endif